# scene
scene: walls #walls simple igibson
scene_id: cross #straight #cross
load_scene_episode_config: false
scene_episode_config_name: null
build_graph: true
load_texture: false #true
pybullet_load_texture: false #true
trav_map_type: no_obj #with_obj
trav_map_resolution: 0.1
trav_map_default_resolution: 0.1
trav_map_erosion: 6
should_open_all_doors: false
not_load_object_categories: [door, carpet]
texture_scale: 0.5
enable_shadow: false
enable_pbr: false

# domain randomization
texture_randomization_freq: null
object_randomization_freq: null

# robot
robot: Custombot #Locobot
is_discrete: false
linear_velocity_high: 0.5
linear_velocity_low: -0.5
angular_velocity: 1.5707963267948966
#velocity: 1.0 # for turtlebot

# task
task: social_nav_random #social_nav_fixed point_nav_fixed
target_dist_min: 1.0
target_dist_max: 10.0
goal_format: polar
task_obs_dim: 24 #6
num_waypoints: 6
waypoint_resolution: 1. #0.1
orca_radius: 0.5
#num_pedestrians: 3
pedestrian_collision_threshold: 0.3

# reward
reward_type: geodesic #geodesic #l2
success_reward: 10.0
potential_reward_weight: 2.0
collision_reward_weight: -10.0
timestep_reward_weight: -0.2
#personal_space_reward: -1

# discount factor
discount_factor: 0.99

# termination condition
dist_tol: 0.36 #0.50 #0.36  # body width
max_step: 500
max_collisions_allowed: 0

# misc config
initial_pos_z_offset: 0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collisions with these robot links
initial_pos: [0, 3.5, 0] #[-2., 0., 0.]
#initial_orn: [0, 1, 0]
target_pos: [0, -4, 0] #[1, -3, 0] #[4, 1, 0]
#ped_target_pos: []
# sensor spec
output: [task_obs, scan]
# image
# Intel Realsense Depth Camera D435
# https://store.intelrealsense.com/buy-intel-realsense-depth-camera-d435.html
fisheye: false
#image_width: 320
#image_height: 180
#vertical_fov: 42.5
image_width: 50 #480 #1024
image_height: 50 #320 #640
vertical_fov: 60.5
# depth
depth_low : 0.1
depth_high: 10.0
# scan
# Hokuyo URG-04LX-UG01
# https://www.hokuyo-aut.jp/search/single.php?serial=166
# n_horizontal_rays is originally 683, sub-sampled 1/3
n_horizontal_rays: 360 #228
n_vertical_beams: 1
laser_linear_range: 5.6
laser_angular_range: 360 #240.0
min_laser_dist: 0.05
laser_link_name: scan_link #camera_link #scan_link #cliff_sensor_front_link

# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0

# visual objects
visual_object_at_initial_target_pos: true
target_visual_object_visible_to_agent: false
