# scene
scene: walls #walls simple igibson
#scene_id: cross #straight #cross
load_scene_episode_config: false
scene_episode_config_name: null
build_graph: true
load_texture: false #true
pybullet_load_texture: false #true
trav_map_type: no_obj #with_obj
trav_map_resolution: 0.1
trav_map_default_resolution: 0.1
trav_map_erosion: 12 #15 #6 #12 #10
should_open_all_doors: false
not_load_object_categories: [door, carpet]
texture_scale: 0.5
enable_shadow: false
enable_pbr: false

# domain randomization
texture_randomization_freq: null
object_randomization_freq: null

# robot
robot: Custombot #Locobot
is_discrete: false
linear_velocity_high: 0.5
linear_velocity_low: -0.1 #-0.5
angular_velocity: 1.5707963267948966

# task
task: social_nav_random
target_dist_min: 1.0
target_dist_max: 50.0
goal_format: polar
num_waypoints: 6 #4 #6
waypoint_resolution: 1.5 #0.6 #1. #0.1
potential_resolution: 0.1
max_num_pedestrians: 8
use_orca: false
orca_radius: 0.3
orca_max_speed: 0.2 #0.3
pedestrian_collision_threshold: 0.3

# reward
reward_type: geodesic
success_reward: 20.0
potential_reward_weight: 5.0
collision_reward_weight: -20.0
timestep_reward_weight: -0.05
personal_space_reward: -2
waypoint_reward: 2. # 0.5

# discount factor
discount_factor: 0.99

# termination condition
dist_tol: 0.36 #0.50 #0.36  # body width
max_step: 500
max_collisions_allowed: 0

# misc config
initial_pos_z_offset: 0.1
collision_ignore_link_a_ids: [1, 2, 3, 4]  # ignore collisions with these robot links

# sensor spec
output: [goal, waypoints, pedestrians, scan]

# scan
# Hokuyo URG-04LX-UG01
# https://www.hokuyo-aut.jp/search/single.php?serial=166
# n_horizontal_rays is originally 683, sub-sampled 1/3
n_horizontal_rays: 120 #360 #228
n_vertical_beams: 1
laser_linear_range: 3.6
laser_angular_range: 360 #240.0
min_laser_dist: 0.05
laser_link_name: scan_link

# image
fisheye: false
image_width: 50 #480 #1024
image_height: 50 #320 #640

# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0

# visual objects
visual_object_at_initial_target_pos: true
target_visual_object_visible_to_agent: false
